version: '3.5'

services:
  loadbalance:
    image: nginx # this will use the latest version of 1.13.x
    container_name: loadbalance
    networks: 
     - default
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
            #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web1:
    image: httpd # this will use the latest version of 1.13.x
    container_name: apache1
    networks: 
     - default
    ports:
      - '8081:80' # expose 80 on host and sent to 80 in container
    volumes:
            #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/local/apache2/htdocs/

  web2:
    image: httpd  # this will use the latest version of 1.13.x
    container_name: apache2
    networks: 
     - default
    ports:
      - '8082:80' # expose 80 on host and sent to 80 in container
    volumes:
            #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html2:/usr/local/apache2/htdocs/

  web3:
    image: httpd # this will use the latest version of 1.13.x
    container_name: apache3
    networks: 
     - default
    ports:
      - '8083:80' # expose 80 on host and sent to 80 in container
    volumes:
            #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html3:/usr/local/apache2/htdocs/


networks:
  default:
   name: mynet
